name: Contribution
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
env:
  OUTPUT_FILE: contribution-graph.svg
  
jobs:
  generate_contribution_graph:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run generate script
        run: bash ./generate moxak ${{ env.OUTPUT_FILE }}