name: Contribution
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  generate_contribution_graph:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run generate script
        run: bash ./generate moxak contribution-graph.svg
      - name: Upload file
        uses: actions/github@v2
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          ref: main
          path: contribution-graph.svg
          message: "Update contribution graph"