name: Contribution
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
env:
  USERNAME: moxak
  OUTPUT_SVG: contribution-graph.svg
  OUTPUT_HTML: index.html
  
jobs:
  generate_contribution_graph:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Generate contribution graph
        run: |
          bash ./generate.sh ${{ env.USERNAME }} ${{ env.OUTPUT_SVG }}
          bash ./generate_html.sh ${{ env.OUTPUT_HTML }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push