name: Contribution
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  generate_contribution_graph:
    runs-on: ubuntu-latest
    steps:
      - run: ./generate