name: Contribution
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
env:
  USERNAME: moxak

  OUTPUT_FILE: contribution-graph.svg
  
jobs:
  generate_contribution_graph:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run generate script
        run: bash ./generate ${{ env.USERNAME }} ${{ env.OUTPUT_FILE }}
      - uses: actions/checkout@v3
      - name: Commit & Pull request
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push